type_map = {
    "Orbit_type": str,
    "a": float,
    "Semilatus_rectum": float,
    "Name": str,
    "Hex_flags": str,
    "Last_obs": str,
    "Synodic_period": float,
    "Epoch": float,
    "Tp": float,
    "e": float,
    "Computer": str,
    "M": float,
    "Aphelion_dist": float,
    "G": float,
    "Peri": float,
    "Arc_years": str,
    "U": str,
    "Number": str,
    "H": float,
    "Other_desigs": list,
    "One_opposition_object_flag": int,
    "Critical_list_numbered_object_flag": int,
    "rms": float,
    "Perturbers": str,
    "Perihelion_dist": float,
    "Num_opps": int,
    "Ref": str,
    "Principal_desig": str,
    "Orbital_period": float,
    "Num_obs": int,
    "Perturbers_2": str,
    "n": float,
    "Node": float,
    "NEO_flag": int,
    "i": float,
    "One_km_NEO_flag": int,
    "Arc_length": int,
    "PHA_flag": int
}

key_map = list(type_map.keys())

compressed_num_map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
