key_map = [
    "Perturbers_2",
    "a",
    "Tp",
    "rms",
    "n",
    "Perturbers",
    "Ref",
    "Num_opps",
    "Synodic_period",
    "e",
    "Aphelion_dist",
    "Epoch",
    "Computer",
    "Other_desigs",
    "Peri",
    "Number",
    "Last_obs",
    "H",
    "G",
    "Perihelion_dist",
    "i",
    "M",
    "Orbit_type",
    "U",
    "Semilatus_rectum",
    "Num_obs",
    "Principal_desig",
    "Node",
    "Arc_years",
    "Orbital_period",
    "Hex_flags",
    "Name",
    "NEO_flag",
    "One_km_NEO_flag",
    "PHA_flag",
    "Critical_list_numbered_object_flag",
    "One_opposition_object_flag",
    "Arc_length"
]

type_map = {
    "Orbit_type": str,
    "a": float,
    "Semilatus_rectum": float,
    "Name": str,
    "Hex_flags": str,
    "Last_obs": str,
    "Synodic_period": float,
    "Epoch": float,
    "Tp": float,
    "e": float,
    "Computer": str,
    "M": float,
    "Aphelion_dist": float,
    "G": float,
    "Peri": float,
    "Arc_years": str,
    "U": str,
    "Number": str,
    "H": float,
    "Other_desigs": list,
    "One_opposition_object_flag": int,
    "Critical_list_numbered_object_flag": int,
    "rms": float,
    "Perturbers": str,
    "Perihelion_dist": float,
    "Num_opps": int,
    "Ref": str,
    "Principal_desig": str,
    "Orbital_period": float,
    "Num_obs": int,
    "Perturbers_2": str,
    "n": float,
    "Node": float,
    "NEO_flag": int,
    "i": float,
    "One_km_NEO_flag": int,
    "Arc_length": int,
    "PHA_flag": int
}

year_map = {
    'K': '20',
    'J': '19',
    'I': '18',
}

month_map = {
    'A': '10',
    'B': '11',
    'C': '12'
}

day_map = {
    'A': '10',
    'B': '11',
    'C': '12',
    'D': '13',
    'E': '14',
    'F': '15',
    'G': '16',
    'H': '17',
    'I': '18',
    'J': '19',
    'K': '20',
    'L': '21',
    'M': '22',
    'N': '23',
    'O': '24',
    'P': '25',
    'Q': '26',
    'R': '27',
    'S': '28',
    'T': '29',
    'U': '30',
    'V': '31',
    'W': '32',
    'X': '33',
    'Y': '34',
    'Z': '35',
    'a': '36',
    'b': '37',
    'c': '38',
    'd': '39',
    'e': '40',
    'f': '41',
    'g': '42',
    'h': '43',
    'i': '44',
    'j': '45',
    'k': '46',
    'l': '47',
    'm': '48',
    'n': '49',
    'o': '50',
    'p': '51',
    'q': '52',
    'r': '53',
    's': '54',
    't': '55',
    'u': '56',
    'v': '57',
    'w': '59',
    'x': '60',
    'y': '61',
    'z': '62'

}
