key_map = [
    "Perturbers_2",
    "a",
    "Tp",
    "rms",
    "n",
    "Perturbers",
    "Ref",
    "Num_opps",
    "Synodic_period",
    "e",
    "Aphelion_dist",
    "Epoch",
    "Computer",
    "Other_desigs",
    "Peri",
    "Number",
    "Last_obs",
    "H",
    "G",
    "Perihelion_dist",
    "i",
    "M",
    "Orbit_type",
    "U",
    "Semilatus_rectum",
    "Num_obs",
    "Principal_desig",
    "Node",
    "Arc_years",
    "Orbital_period",
    "Hex_flags",
    "Name",
    "NEO_flag",
    "One_km_NEO_flag",
    "PHA_flag",
    "Critical_list_numbered_object_flag",
    "One_opposition_object_flag",
    "Arc_length"
]

type_map = {
    "Orbit_type": str,
    "a": float,
    "Semilatus_rectum": float,
    "Name": str,
    "Hex_flags": str,
    "Last_obs": str,
    "Synodic_period": float,
    "Epoch": float,
    "Tp": float,
    "e": float,
    "Computer": str,
    "M": float,
    "Aphelion_dist": float,
    "G": float,
    "Peri": float,
    "Arc_years": str,
    "U": str,
    "Number": str,
    "H": float,
    "Other_desigs": list,
    "One_opposition_object_flag": int,
    "Critical_list_numbered_object_flag": int,
    "rms": float,
    "Perturbers": str,
    "Perihelion_dist": float,
    "Num_opps": int,
    "Ref": str,
    "Principal_desig": str,
    "Orbital_period": float,
    "Num_obs": int,
    "Perturbers_2": str,
    "n": float,
    "Node": float,
    "NEO_flag": int,
    "i": float,
    "One_km_NEO_flag": int,
    "Arc_length": int,
    "PHA_flag": int
}


compressed_num_map = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz'
